"""add google_id and make password_hash nullable

Revision ID: 92eecf04e2ec
Revises: c9acc2eeb8ce
Create Date: 2026-08-22 12:45:16.325054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92eecf04e2ec'
down_revision = 'c9acc2eeb8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=250), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
